import{useEffect,useRef,useState}from"react";import{FolderOpen,Play,Pause,SkipBack,SkipForward,Volume2,VolumeX,Maximize,RotateCcw,Shuffle,Repeat,Music2,Film,Trash2}from"lucide-react";
type Item={id:string;name:string;url:string;kind:"audio"|"video";size:number};
const audioExt=/\.(mp3|wav|flac|m4a|aac|ogg|oga|opus|weba|aiff|aif|alac)$/i;
const videoExt=/\.(mp4|webm|ogv|mov|m4v|mkv|avi)$/i;
export function Player(){const media=useRef<HTMLMediaElement>(null);const input=useRef<HTMLInputElement>(null);const[items,setItems]=useState<Item[]>([]);const[index,setIndex]=useState(0);const[playing,setPlaying]=useState(false);const[muted,setMuted]=useState(false);const[shuffle,setShuffle]=useState(false);const[repeat,setRepeat]=useState(false);const[volume,setVolume]=useState(1);const current=items[index];
useEffect(()=>{if(!current)return;media.current?.load();if(playing)media.current?.play().catch(()=>{});},[current]);
useEffect(()=>{if(media.current)media.current.volume=volume;},[volume]);
useEffect(()=>{const m=media.current;if(!m)return;const onPlay=()=>setPlaying(true),onPause=()=>setPlaying(false),onEnd=()=>{if(repeat){m.currentTime=0;m.play();return}next()};m.addEventListener("play",onPlay);m.addEventListener("pause",onPause);m.addEventListener("ended",onEnd);return()=>{m.removeEventListener("play",onPlay);m.removeEventListener("pause",onPause);m.removeEventListener("ended",onEnd)}},[index,repeat,shuffle,items.length]);
useEffect(()=>{if("mediaSession"in navigator&&current){navigator.mediaSession.metadata=new MediaMetadata({title:current.name,artist:"Mortimer Player"});navigator.mediaSession.setActionHandler("play",()=>media.current?.play());navigator.mediaSession.setActionHandler("pause",()=>media.current?.pause());navigator.mediaSession.setActionHandler("previoustrack",prev);navigator.mediaSession.setActionHandler("nexttrack",next)}},[current]);
function addFiles(list:FileList|null){if(!list)return;const next=[...list].filter(f=>audioExt.test(f.name)||videoExt.test(f.name)).map(f=>({id:crypto.randomUUID(),name:f.name,url:URL.createObjectURL(f),kind:videoExt.test(f.name)?"video":"audio",size:f.size}));setItems(x=>[...x,...next]);if(!current&&next.length)setIndex(0)}
function next(){if(!items.length)return;setIndex(i=>shuffle?Math.floor(Math.random()*items.length):(i+1)%items.length)}
function prev(){if(!items.length)return;const m=media.current;if(m&&m.currentTime>3){m.currentTime=0;return}setIndex(i=>(i-1+items.length)%items.length)}
function toggle(){if(!media.current)return;playing?media.current.pause():media.current.play().catch(()=>{})}
function clear(){items.forEach(x=>URL.revokeObjectURL(x.url));setItems([]);setIndex(0);setPlaying(false)}
return <main className="app"><header><div className="brand"><div className="logo"><Play size={18} fill="currentColor"/></div><div><b>Mortimer</b><span>PLAYER</span></div></div><button className="open" onClick={()=>input.current?.click()}><FolderOpen size={18}/> Open media</button><input ref={input} hidden type="file" multiple accept="audio/*,video/*,.flac,.mkv,.avi,.mov" onChange={e=>addFiles(e.target.files)}/></header>
<section className="stage">{current?.kind==="video"?<video ref={media as React.RefObject<HTMLVideoElement>} src={current.url} playsInline controls={false}/>:<div className="art"><Music2 size={72}/><strong>{current?.name||"Mortimer Player"}</strong><small>{current?"Ready to play":"Open audio or video files to begin"}</small></div>}{current&&current.kind==="audio"&&<audio ref={media as React.RefObject<HTMLAudioElement>} src={current.url}/>}</section>
<section className="now"><div><span>NOW PLAYING</span><h1>{current?.name||"Nothing selected"}</h1><p>{current?current.kind.toUpperCase():"Select media from your device"}</p></div><button onClick={()=>current&&setItems(x=>x.filter((_,i)=>i!==index))} disabled={!current}><Trash2 size={18}/></button></section>
<div className="progress"><span>{format(media.current?.currentTime||0)}</span><input type="range" min="0" max={media.current?.duration||0} step=".1" value={media.current?.currentTime||0} onChange={e=>{if(media.current)media.current.currentTime=+e.target.value}}/><span>{format(media.current?.duration||0)}</span></div>
<nav className="controls"><button className={shuffle?"active":""} onClick={()=>setShuffle(x=>!x)}><Shuffle/></button><button onClick={prev}><SkipBack/></button><button className="play" onClick={toggle} disabled={!current}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button onClick={next}><SkipForward/></button><button className={repeat?"active":""} onClick={()=>setRepeat(x=>!x)}><Repeat/></button></nav>
<div className="bottom"><div className="volume"><button onClick={()=>setMuted(x=>!x)}>{muted?<VolumeX/>:<Volume2/>}</button><input type="range" min="0" max="1" step=".01" value={muted?0:volume} onChange={e=>{setMuted(false);setVolume(+e.target.value)}}/></div>{current?.kind==="video"&&<button onClick={()=>{const v=media.current as HTMLVideoElement;if(v.requestFullscreen)v.requestFullscreen()}}><Maximize/></button>}<button onClick={clear} disabled={!items.length}><RotateCcw/></button></div>
<section className="queue"><div className="queueTitle"><b>QUEUE</b><span>{items.length} items</span></div>{items.map((x,i)=><button className={"row "+(i===index?"selected":"")} key={x.id} onClick={()=>setIndex(i)}><span>{x.kind==="video"?<Film/>:<Music2/>}</span><div><b>{x.name}</b><small>{x.kind}</small></div></button>)}</section></main>}
function format(n:number){if(!isFinite(n))return"0:00";return Math.floor(n/60)+":"+String(Math.floor(n%60)).padStart(2,"0")}